package cz.cuni.mff.webservices.soap.cardverification;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2022-03-23T20:08:06.831+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "CardVerifierService", 
                  wsdlLocation = "file:/C:/Users/Andrej/Desktop/Sync/LS22/web-services/NSWI145-web-services/05-cxf/src/main/resources/cardverificator.wsdl",
                  targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/") 
public class CardVerifierService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cardverification.soap.webservices.mff.cuni.cz/", "CardVerifierService");
    public final static QName CardVerifierPort = new QName("http://cardverification.soap.webservices.mff.cuni.cz/", "CardVerifierPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Andrej/Desktop/Sync/LS22/web-services/NSWI145-web-services/05-cxf/src/main/resources/cardverificator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CardVerifierService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Andrej/Desktop/Sync/LS22/web-services/NSWI145-web-services/05-cxf/src/main/resources/cardverificator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CardVerifierService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CardVerifierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardVerifierService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardVerifierService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardVerifierService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardVerifierService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICardVerifier
     */
    @WebEndpoint(name = "CardVerifierPort")
    public ICardVerifier getCardVerifierPort() {
        return super.getPort(CardVerifierPort, ICardVerifier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICardVerifier
     */
    @WebEndpoint(name = "CardVerifierPort")
    public ICardVerifier getCardVerifierPort(WebServiceFeature... features) {
        return super.getPort(CardVerifierPort, ICardVerifier.class, features);
    }

}
