package cz.cuni.mff.webservices.soap.cardverification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2022-03-23T20:08:06.823+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/", name = "ICardVerifier")
@XmlSeeAlso({ObjectFactory.class})
public interface ICardVerifier {

    @WebMethod
    @RequestWrapper(localName = "verify", targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/", className = "cz.cuni.mff.webservices.soap.cz.cuni.mff.webservices.soap.cardverification.Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/", className = "cz.cuni.mff.webservices.soap.cz.cuni.mff.webservices.soap.cardverification.VerifyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean verify(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addCard", targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/", className = "cz.cuni.mff.webservices.soap.cz.cuni.mff.webservices.soap.cardverification.AddCard")
    @ResponseWrapper(localName = "addCardResponse", targetNamespace = "http://cardverification.soap.webservices.mff.cuni.cz/", className = "cz.cuni.mff.webservices.soap.cz.cuni.mff.webservices.soap.cardverification.AddCardResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
