
package cz.cuni.mff.webservices.soap.cardverification;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2022-03-23T20:08:06.774+01:00
 * Generated source version: 2.7.18
 * 
 */
public final class ICardVerifier_CardVerifierPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cardverification.soap.webservices.mff.cuni.cz/", "CardVerifierService");

    private ICardVerifier_CardVerifierPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CardVerifierService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CardVerifierService ss = new CardVerifierService(wsdlURL, SERVICE_NAME);
        ICardVerifier port = ss.getCardVerifierPort();  
        
        {
        System.out.println("Invoking verify...");
        java.lang.String _verify_arg0 = "";
        boolean _verify__return = port.verify(_verify_arg0);
        System.out.println("verify.result=" + _verify__return);


        }
        {
        System.out.println("Invoking addCard...");
        java.lang.String _addCard_arg0 = "";
        boolean _addCard__return = port.addCard(_addCard_arg0);
        System.out.println("addCard.result=" + _addCard__return);


        }

        System.exit(0);
    }

}
