
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.webservices.soap.cardverification;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2022-03-23T12:15:08.324+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(endpointInterface = "cz.cuni.mff.webservices.soap.cardverification.ICardVerifier", serviceName = "ICardVerifierService")                      
public class ICardVerifierImpl implements ICardVerifier {

    public boolean verify(java.lang.String arg0) {  
        System.out.println(arg0);    
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }


    public boolean addCard(java.lang.String arg0) {  
        System.out.println(arg0);    
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }

}