
package cz.cuni.mff.webservices.soap.cardverification;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2022-03-23T20:08:12.260+01:00
 * Generated source version: 2.7.9
 * 
 */
 
public class ICardVerifierServer{

    protected ICardVerifierServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new cz.cuni.mff.webservices.soap.cardverification.ICardVerifierImpl();
        String address = "http://127.0.0.1:8000/verification";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ICardVerifierServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 